# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(535, 389)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnBackup = QtWidgets.QPushButton(self.centralwidget)
        self.btnBackup.setGeometry(QtCore.QRect(20, 110, 81, 31))
        self.btnBackup.setObjectName("btnBackup")
        self.btnInspect = QtWidgets.QPushButton(self.centralwidget)
        self.btnInspect.setGeometry(QtCore.QRect(20, 60, 81, 31))
        self.btnInspect.setObjectName("btnInspect")
        self.listDevice = QtWidgets.QListView(self.centralwidget)
        self.listDevice.setGeometry(QtCore.QRect(240, 10, 281, 181))
        self.listDevice.setObjectName("listDevice")
        self.listLog = QtWidgets.QListView(self.centralwidget)
        self.listLog.setGeometry(QtCore.QRect(10, 200, 511, 141))
        self.listLog.setObjectName("listLog")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 535, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnBackup.setText(_translate("MainWindow", "BackUp"))
        self.btnInspect.setText(_translate("MainWindow", "Inspect"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
    
    def set_btn_inspect_listener(self, btn_inspect_acction):
        self.btnInspect.connect(btn_inspect_acction)
    
    def set_btn_backup_listener(self, btn_backup_acction):
        self.btnBackup.connect(btn_btnBackup_acction)
    
    def set_list_item(self, entries):
        model = QtGui.QStandardItemModel()
        self.listDevice.setFlow(QtWidgets.QListView.LeftToRight)
        self.listDevice.setModel(model)
        
        for value in entries['value']:
            item = QtGui.QStandardItem(value)
            model.appendRow(item)
        
        # for col in entries['column']:
        #     item = QtGui.QStandardItem(col)
        #     model.appendColumn(item)
            
