# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(582, 444)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnBackup = QtWidgets.QPushButton(self.centralwidget)
        self.btnBackup.setGeometry(QtCore.QRect(20, 110, 81, 31))
        self.btnBackup.setObjectName("btnBackup")
        self.btnInspect = QtWidgets.QPushButton(self.centralwidget)
        self.btnInspect.setGeometry(QtCore.QRect(20, 60, 81, 31))
        self.btnInspect.setObjectName("btnInspect")
        self.listLog = QtWidgets.QListView(self.centralwidget)
        self.listLog.setGeometry(QtCore.QRect(20, 260, 551, 141))
        self.listLog.setObjectName("listLog")
        self.tableDevice = QtWidgets.QTableView(self.centralwidget)
        self.tableDevice.setGeometry(QtCore.QRect(150, 40, 411, 191))
        self.tableDevice.setMouseTracking(True)
        self.tableDevice.setTabletTracking(True)
        self.tableDevice.setObjectName("tableDevice")
        self.tableDeviceLabel = QtWidgets.QLabel(self.centralwidget)
        self.tableDeviceLabel.setGeometry(QtCore.QRect(150, 20, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tableDeviceLabel.setFont(font)
        self.tableDeviceLabel.setObjectName("tableDeviceLabel")
        self.listLoglabel = QtWidgets.QLabel(self.centralwidget)
        self.listLoglabel.setGeometry(QtCore.QRect(20, 240, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.listLoglabel.setFont(font)
        self.listLoglabel.setObjectName("listLoglabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 582, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnBackup.setText(_translate("MainWindow", "BackUp"))
        self.btnInspect.setText(_translate("MainWindow", "Inspect"))
        self.tableDeviceLabel.setText(_translate("MainWindow", "Active Devices"))
        self.listLoglabel.setText(_translate("MainWindow", "Status"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))

    def set_btn_inspect_listener(self, list_entries):
        self.btnInspect.clicked.connect(self.set_list_log(list_entries))
    
    def set_btn_backup_listener(self, button_action):
        self.btnBackup.clicked.connect(button_action)
    
    def set_table_item(self, entries):
        self.tableDevice.setShowGrid(False)
        model = QtGui.QStandardItemModel()
        model.setVerticalHeaderLabels(entries['column'])
        self.tableDevice.setModel(model)
        for value in entries['value']:
            item = QtGui.QStandardItem(value)
            item.setEditable(False)
            model.appendColumn([item])
    
    def set_list_log(self, entries):
        model = QtGui.QStandardItemModel()
        self.listLog.setModel(model)
        
        for value in entries:
            item = QtGui.QStandardItem(value)
            model.appendRow(item)